apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod # This name is referenced by your Ingress
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: bachlx2004@gmail.com
    privateKeySecretRef:
      name: erpnext-tls
    solvers:
    - http01:
        ingress:
          class: nginx # Your ingress class